on: push
name: golang-ci
jobs:
  checks:
    name: run-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Go 1.15
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: "on"

      - name: Use Go 1.14
        uses: cedrickring/golang-action/go1.14@1.6.0
        env:
          GO111MODULE: "on"